## YAML Template.
---

server:
    port: 48152
    
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: false
        
custom: 
    activeprofileName: production
    
spring:
    application:
        name: customer
    jpa:
        show-sql: true
    datasource:
        url: jdbc:h2:mem:customer
        username: sa
        password: qwerty
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
        
    